version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./init.sql:/data/application/init.sql
    networks:
      - db-link
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: logsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    command: --init-file /data/application/init.sql


  web:
    build: .
    image: "smart-logs-api:latest"
    networks:
      - db-link
    ports:
     - "8080:8080"
    links:
      - db
    depends_on:
      - db
    command: ["java", "-jar", "./target/smart-logs-api.jar"]

networks:
  db-link: